name: Build and deploy Node.js app to Azure Web App - healthcure-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'healthcure-backend'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_30E3F8FC84CA4D26A4A8B926B3162D5C }}

      - name: Send Teams notification
        if: always()
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.INCOMING_WEBHOOK }}
        run: |
          STATUS="Deployment succeeded"
          if [ "${{ job.status }}" != "success" ]; then
            STATUS="Deployment failed"
          fi
          curl -H "Content-Type: application/json" \
               -d "{\"text\": \"${STATUS} to Azure Web App *healthcure-backend* by Srinivas\"}" \
               "$INCOMING_WEBHOOK"
