name: Build and deploy Node.js app to Azure Web App - healthcure-backend

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      # Inject environment variables into Azure App Settings
      - name: Set Azure App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: 'healthcure-backend'
          app-settings-json: |
            [
              { "name": "JWT_SECRET", "value": "${{ secrets.JWT_SECRET }}" },
              { "name": "MONGO_URI",  "value": "${{ secrets.MONGO_URI }}" },
              { "name": "PORT",       "value": "${{ secrets.PORT }}" }
            ]

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'healthcure-backend'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4FE7B843C0314AA49975FC2BE13511F4 }}

      #  Send Teams notification on success
      - name: Send Teams success notification
        if: success()
        run: |
          curl -H 'Content-Type: application/json' \
          -d '{
            "@type": "MessageCard",
            "@context": "https://schema.org/extensions",
            "summary": "Deployment Success",
            "themeColor": "0078D7",
            "title": "Deployment Successful",
            "text": "The Node.js backend **healthcure-backend** was deployed successfully to Azure Web App.\n\nDeployed by **Srinivas Reddy**."
          }' \
          ${{ secrets.TEAMS_WEBHOOK_URL }}

      # Send Teams notification on failure
      - name: Send Teams failure notification
        if: failure()
        run: |
          curl -H 'Content-Type: application/json' \
          -d '{
            "@type": "MessageCard",
            "@context": "https://schema.org/extensions",
            "summary": "Deployment Failed",
            "themeColor": "FF0000",
            "title": "Deployment Failed",
            "text": "The Node.js backend **healthcure-backend** deployment to Azure Web App has failed.\n\nDeployed by **Srinivas Reddy**. Please check the workflow logs for details."
          }' \
          ${{ secrets.INCOMING_WEBHOOK }}
